### ISSUE TITLE
Using different port causes 404

### ISSUE THREAD

**Issue by raffazizzi** [peterstadler/oxgarage-docker#3]
I tried running the service with `-p 8081:8080` and it appeared to run correctly, but some resources returned `404`. The service works as expected with `-p 8080:8080`.

`http://localhost:8081/ege-webclient/` was reachable, but `/Conversions/` and `/Validations/` returned `404`, see screenshot below.

![screenshot from 2017-12-26 12-57-14](https://user-images.githubusercontent.com/144770/34361953-04807c84-ea3d-11e7-96e9-cd8b9dc52011.png)

**Comment by peterstadler** [comment]
Yes, that's a little bit annoying but due to the fact that there are actually two 'services' running within one container: 
* the webclient, i.e. the GUI
* and the webservice, i.e. the REST interface

The GUI needs to know where the webservice listens but at present I see no way to dynamically read in this information :(
The simplest solution probably is to duplicate this information as an environment variable which is then read by a script which alters https://github.com/TEIC/oxgarage/blob/25748855ee52f987c075a014a076a53ce7c0ce9f/ege-webclient/src/main/webapp/WEB-INF/web.xml#L10  (within the container, during startup)

E.g. `docker run … -e WEBSERVICE_URL=http://localhost:8081/ege-webservice/`

Does that make sense?

**Comment by raffazizzi** [comment]
Sounds good to me, thanks!
